lib/kanbax_web/router.ex
defmodule KanbaxWeb.Router do
  use KanbaxWeb, :router

  import KanbaxWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {KanbaxWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", KanbaxWeb do
    pipe_through :browser

  end

  # Other scopes may use custom stacks.
  # scope "/api", KanbaxWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: KanbaxWeb.Telemetry
    end
  end

  ## Authentication routes

  scope "/", KanbaxWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", KanbaxWeb do
    pipe_through [:browser, :require_authenticated_user]
    live "/", PageLive, :index

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email

    live "/status", StatusLive.Index, :index
    live "/status/new", StatusLive.Index, :new
    live "/status/:id/edit", StatusLive.Index, :edit

    live "/status/:id", StatusLive.Show, :show
    live "/status/:id/show/edit", StatusLive.Show, :edit

    live "/new", PageLive, :new
    live "/:id/edit", PageLive, :edit

    live "/tasks", TaskLive.Index, :index
    live "/tasks/new", TaskLive.Index, :new
    live "/tasks/:id/edit", TaskLive.Index, :edit

    live "/tasks/:id", TaskLive.Show, :show
    live "/tasks/:id/show/edit", TaskLive.Show, :edit
  end

  scope "/", KanbaxWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :confirm
  end
end

lib/kanbax_web/views/layout_view.ex
defmodule KanbaxWeb.LayoutView do
  use KanbaxWeb, :view
end

lib/kanbax_web/templates/layout/_user_menu.html.eex
<ul style="display:flex; justify-content: space-between; display: flex; padding-top: 46px">
<%= if @current_user do %>

  <li><%= @current_user.name %></li>
  <li><%= live_patch "Nova Tarefa", to: Routes.page_path(@conn, :new) %></li>

  <!--<li><%= link "Configurações", to: Routes.user_settings_path(@conn, :edit) %></li>-->
  <li><%= link "Sair", to: Routes.user_session_path(@conn, :delete), method: :delete %></li>

<% else %>
  <li><%= link "Cadastrar", to: Routes.user_registration_path(@conn, :new) %></li>
  <li><%= link "Fazer login", to: Routes.user_session_path(@conn, :new) %></li>
<% end %>
</ul>

lib/kanbax_web/templates/layout/app.html.eex
<main role="main" class="container">
  <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
  <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
  <%= @inner_content %>
</main>

lib/kanbax_web/templates/layout/live.html.leex
<main role="main">
  <p class="alert alert-info" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="info"><%= live_flash(@flash, :info) %></p>

  <p class="alert alert-danger" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error"><%= live_flash(@flash, :error) %></p>

  <%= @inner_content %>
</main>

lib/kanbax_web/templates/layout/root.html.leex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <%= csrf_meta_tag() %>
    <%= live_title_tag assigns[:page_title] || "Kanbax", suffix: " · Phoenix Framework" %>
    <!--Import Google Icon Font-->
      <link phx-track-static rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <script defer phx-track-static type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
    <style>
    *{
      margin: 0;
      padding: 0;
      box-sizing: border-box;
      }

    nav.user-header li{
        font-size: 20px;

    }

    .center{
      max-width: 1280px;
      margin: 0 auto;
    }

    .header{
      display: flex;
      justify-content: space-between;
      border: 0;
    }

    .edit-image{
      width: 24px;
      height: 24px;
    }
    </style>
  </head>
  <body>
    <header style="; background-color: #2196f3;">
      <div class="center">
        <div class="header">
        <div style="flex: 11"><img src="/images/logo.png" style="width:248px; height:128px"></div>
        <nav class="user-header" style="flex: 11">
          <%= render "_user_menu.html", assigns %>
        </nav>
        </div>
      </div>
    </header>
    <%= @inner_content %>
  </body>
</html>